apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tomcat
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/AMK/sample.war"
